// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/envelope.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventEnvelope 是所有 Kafka 消息的统一外层包装。
// 消费方可通过 event_type 做路由，payload 内嵌具体事件 proto 的序列化字节。
//
// 使用场景：需要跨服务统一元数据时使用；单服务内部 topic 可直接使用具体事件消息体。
type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`             // UUID v4，全局唯一事件 ID
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`       // 完整 topic 名，如 "brokerage.market-data.quote.updated"
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                              // 发布服务名，如 "market-data"
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"` // 发布时间（UTC）
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`                            // 具体事件消息体的 proto 序列化字节
	TraceId       string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`             // OTel Trace ID，用于分布式追踪关联
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_events_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventEnvelope) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_events_v1_envelope_proto protoreflect.FileDescriptor

const file_events_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18events/v1/envelope.proto\x12\x13brokerage.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12=\n" +
	"\fpublished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceIdB6Z4github.com/hxiaodon/ai-broker/api/events/v1;eventsv1b\x06proto3"

var (
	file_events_v1_envelope_proto_rawDescOnce sync.Once
	file_events_v1_envelope_proto_rawDescData []byte
)

func file_events_v1_envelope_proto_rawDescGZIP() []byte {
	file_events_v1_envelope_proto_rawDescOnce.Do(func() {
		file_events_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_envelope_proto_rawDesc), len(file_events_v1_envelope_proto_rawDesc)))
	})
	return file_events_v1_envelope_proto_rawDescData
}

var file_events_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil),         // 0: brokerage.events.v1.EventEnvelope
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_events_v1_envelope_proto_depIdxs = []int32{
	1, // 0: brokerage.events.v1.EventEnvelope.published_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_v1_envelope_proto_init() }
func file_events_v1_envelope_proto_init() {
	if File_events_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_envelope_proto_rawDesc), len(file_events_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_envelope_proto_goTypes,
		DependencyIndexes: file_events_v1_envelope_proto_depIdxs,
		MessageInfos:      file_events_v1_envelope_proto_msgTypes,
	}.Build()
	File_events_v1_envelope_proto = out.File
	file_events_v1_envelope_proto_goTypes = nil
	file_events_v1_envelope_proto_depIdxs = nil
}
