// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/v1/market_events.proto

package eventsv1

import (
	v1 "github.com/hxiaodon/ai-broker/api/market_data/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QuoteUpdatedEvent 是 Kafka topic brokerage.market-data.quote.updated 的消息体。
// 每次 feed handler 收到新 tick 时由 Outbox Worker 发布。
//
// 消费方：
//
//	Trading Engine — 维护内部报价缓存，用于批量风控计算
//
// 幂等保证：
//
//	消费方使用 event_id（UUID v4）做幂等去重，处理前先检查是否已处理过。
type QuoteUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`          // UUID v4，消费方幂等去重键
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // 事件发生时间（UTC）；JSON encoding → RFC 3339
	Quote         *v1.Quote              `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`                             // 完整行情快照
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteUpdatedEvent) Reset() {
	*x = QuoteUpdatedEvent{}
	mi := &file_events_v1_market_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteUpdatedEvent) ProtoMessage() {}

func (x *QuoteUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_market_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteUpdatedEvent.ProtoReflect.Descriptor instead.
func (*QuoteUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_market_events_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteUpdatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QuoteUpdatedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *QuoteUpdatedEvent) GetQuote() *v1.Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_events_v1_market_events_proto protoreflect.FileDescriptor

const file_events_v1_market_events_proto_rawDesc = "" +
	"\n" +
	"\x1devents/v1/market_events.proto\x12\x13brokerage.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a market_data/v1/market_data.proto\"\xa2\x01\n" +
	"\x11QuoteUpdatedEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12;\n" +
	"\voccurred_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x125\n" +
	"\x05quote\x18\x03 \x01(\v2\x1f.brokerage.market_data.v1.QuoteR\x05quoteB6Z4github.com/hxiaodon/ai-broker/api/events/v1;eventsv1b\x06proto3"

var (
	file_events_v1_market_events_proto_rawDescOnce sync.Once
	file_events_v1_market_events_proto_rawDescData []byte
)

func file_events_v1_market_events_proto_rawDescGZIP() []byte {
	file_events_v1_market_events_proto_rawDescOnce.Do(func() {
		file_events_v1_market_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_market_events_proto_rawDesc), len(file_events_v1_market_events_proto_rawDesc)))
	})
	return file_events_v1_market_events_proto_rawDescData
}

var file_events_v1_market_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_market_events_proto_goTypes = []any{
	(*QuoteUpdatedEvent)(nil),     // 0: brokerage.events.v1.QuoteUpdatedEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*v1.Quote)(nil),              // 2: brokerage.market_data.v1.Quote
}
var file_events_v1_market_events_proto_depIdxs = []int32{
	1, // 0: brokerage.events.v1.QuoteUpdatedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2, // 1: brokerage.events.v1.QuoteUpdatedEvent.quote:type_name -> brokerage.market_data.v1.Quote
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_v1_market_events_proto_init() }
func file_events_v1_market_events_proto_init() {
	if File_events_v1_market_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_market_events_proto_rawDesc), len(file_events_v1_market_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_market_events_proto_goTypes,
		DependencyIndexes: file_events_v1_market_events_proto_depIdxs,
		MessageInfos:      file_events_v1_market_events_proto_msgTypes,
	}.Build()
	File_events_v1_market_events_proto = out.File
	file_events_v1_market_events_proto_goTypes = nil
	file_events_v1_market_events_proto_depIdxs = nil
}
