// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: market_data/v1/errors.proto

package market_datav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarketDataErrorReason 定义 Market Data 服务的领域错误码。
// 命名规范：MARKET_DATA_{ENTITY}_{REASON}
// 错误码只追加，禁止重新编号或删除（append-only）。
//
// HTTP 状态码映射（由 Kratos errors 中间件处理，集成时恢复注解）：
//
//	INVALID_ARGUMENT    → 400
//	SYMBOL_NOT_FOUND    → 404
//	UNAUTHORIZED        → 401
//	RATE_LIMITED        → 429
//	STALE               → 412
//	FEED_UNAVAILABLE    → 503
//	INTERNAL            → 500
type MarketDataErrorReason int32

const (
	MarketDataErrorReason_MARKET_DATA_ERROR_REASON_UNSPECIFIED MarketDataErrorReason = 0
	MarketDataErrorReason_MARKET_DATA_INVALID_ARGUMENT         MarketDataErrorReason = 1  // 请求参数非法（如 symbol 格式错误）
	MarketDataErrorReason_MARKET_DATA_SYMBOL_NOT_FOUND         MarketDataErrorReason = 2  // symbol 不存在或未收录
	MarketDataErrorReason_MARKET_DATA_UNAUTHORIZED             MarketDataErrorReason = 3  // 未认证（WebSocket auth 失败）
	MarketDataErrorReason_MARKET_DATA_RATE_LIMITED             MarketDataErrorReason = 4  // 超过频率限制（100 req/s per IP）
	MarketDataErrorReason_MARKET_DATA_STALE                    MarketDataErrorReason = 5  // 数据超过交易风控阈值 1s，拒绝市价单
	MarketDataErrorReason_MARKET_DATA_FEED_UNAVAILABLE         MarketDataErrorReason = 10 // 上游 feed（Polygon/HKEX）不可用
	MarketDataErrorReason_MARKET_DATA_INTERNAL                 MarketDataErrorReason = 11 // 内部错误
)

// Enum value maps for MarketDataErrorReason.
var (
	MarketDataErrorReason_name = map[int32]string{
		0:  "MARKET_DATA_ERROR_REASON_UNSPECIFIED",
		1:  "MARKET_DATA_INVALID_ARGUMENT",
		2:  "MARKET_DATA_SYMBOL_NOT_FOUND",
		3:  "MARKET_DATA_UNAUTHORIZED",
		4:  "MARKET_DATA_RATE_LIMITED",
		5:  "MARKET_DATA_STALE",
		10: "MARKET_DATA_FEED_UNAVAILABLE",
		11: "MARKET_DATA_INTERNAL",
	}
	MarketDataErrorReason_value = map[string]int32{
		"MARKET_DATA_ERROR_REASON_UNSPECIFIED": 0,
		"MARKET_DATA_INVALID_ARGUMENT":         1,
		"MARKET_DATA_SYMBOL_NOT_FOUND":         2,
		"MARKET_DATA_UNAUTHORIZED":             3,
		"MARKET_DATA_RATE_LIMITED":             4,
		"MARKET_DATA_STALE":                    5,
		"MARKET_DATA_FEED_UNAVAILABLE":         10,
		"MARKET_DATA_INTERNAL":                 11,
	}
)

func (x MarketDataErrorReason) Enum() *MarketDataErrorReason {
	p := new(MarketDataErrorReason)
	*p = x
	return p
}

func (x MarketDataErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketDataErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_v1_errors_proto_enumTypes[0].Descriptor()
}

func (MarketDataErrorReason) Type() protoreflect.EnumType {
	return &file_market_data_v1_errors_proto_enumTypes[0]
}

func (x MarketDataErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketDataErrorReason.Descriptor instead.
func (MarketDataErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_market_data_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_market_data_v1_errors_proto protoreflect.FileDescriptor

const file_market_data_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1bmarket_data/v1/errors.proto\x12\x18brokerage.market_data.v1*\x94\x02\n" +
	"\x15MarketDataErrorReason\x12(\n" +
	"$MARKET_DATA_ERROR_REASON_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMARKET_DATA_INVALID_ARGUMENT\x10\x01\x12 \n" +
	"\x1cMARKET_DATA_SYMBOL_NOT_FOUND\x10\x02\x12\x1c\n" +
	"\x18MARKET_DATA_UNAUTHORIZED\x10\x03\x12\x1c\n" +
	"\x18MARKET_DATA_RATE_LIMITED\x10\x04\x12\x15\n" +
	"\x11MARKET_DATA_STALE\x10\x05\x12 \n" +
	"\x1cMARKET_DATA_FEED_UNAVAILABLE\x10\n" +
	"\x12\x18\n" +
	"\x14MARKET_DATA_INTERNAL\x10\vB@Z>github.com/hxiaodon/ai-broker/api/market_data/v1;market_datav1b\x06proto3"

var (
	file_market_data_v1_errors_proto_rawDescOnce sync.Once
	file_market_data_v1_errors_proto_rawDescData []byte
)

func file_market_data_v1_errors_proto_rawDescGZIP() []byte {
	file_market_data_v1_errors_proto_rawDescOnce.Do(func() {
		file_market_data_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_v1_errors_proto_rawDesc), len(file_market_data_v1_errors_proto_rawDesc)))
	})
	return file_market_data_v1_errors_proto_rawDescData
}

var file_market_data_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_market_data_v1_errors_proto_goTypes = []any{
	(MarketDataErrorReason)(0), // 0: brokerage.market_data.v1.MarketDataErrorReason
}
var file_market_data_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_data_v1_errors_proto_init() }
func file_market_data_v1_errors_proto_init() {
	if File_market_data_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_v1_errors_proto_rawDesc), len(file_market_data_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_data_v1_errors_proto_goTypes,
		DependencyIndexes: file_market_data_v1_errors_proto_depIdxs,
		EnumInfos:         file_market_data_v1_errors_proto_enumTypes,
	}.Build()
	File_market_data_v1_errors_proto = out.File
	file_market_data_v1_errors_proto_goTypes = nil
	file_market_data_v1_errors_proto_depIdxs = nil
}
