// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: market_data/v1/market_data.proto

package market_datav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Market 标识交易所所在市场（来源：market-api-spec.md §1.4）
type Market int32

const (
	Market_MARKET_UNSPECIFIED Market = 0
	Market_MARKET_US          Market = 1 // NYSE / NASDAQ
	Market_MARKET_HK          Market = 2 // HKEX
)

// Enum value maps for Market.
var (
	Market_name = map[int32]string{
		0: "MARKET_UNSPECIFIED",
		1: "MARKET_US",
		2: "MARKET_HK",
	}
	Market_value = map[string]int32{
		"MARKET_UNSPECIFIED": 0,
		"MARKET_US":          1,
		"MARKET_HK":          2,
	}
)

func (x Market) Enum() *Market {
	p := new(Market)
	*p = x
	return p
}

func (x Market) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Market) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_v1_market_data_proto_enumTypes[0].Descriptor()
}

func (Market) Type() protoreflect.EnumType {
	return &file_market_data_v1_market_data_proto_enumTypes[0]
}

func (x Market) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Market.Descriptor instead.
func (Market) EnumDescriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{0}
}

// MarketStatus 标识当前交易时段（来源：market-api-spec.md §1.4）
type MarketStatus int32

const (
	MarketStatus_MARKET_STATUS_UNSPECIFIED MarketStatus = 0
	MarketStatus_MARKET_STATUS_REGULAR     MarketStatus = 1 // 常规交易时段
	MarketStatus_MARKET_STATUS_PRE_MARKET  MarketStatus = 2 // 盘前交易（美股）
	MarketStatus_MARKET_STATUS_AFTER_HOURS MarketStatus = 3 // 盘后交易（美股）
	MarketStatus_MARKET_STATUS_CLOSED      MarketStatus = 4 // 已收盘
	MarketStatus_MARKET_STATUS_HALTED      MarketStatus = 5 // 临时停牌
)

// Enum value maps for MarketStatus.
var (
	MarketStatus_name = map[int32]string{
		0: "MARKET_STATUS_UNSPECIFIED",
		1: "MARKET_STATUS_REGULAR",
		2: "MARKET_STATUS_PRE_MARKET",
		3: "MARKET_STATUS_AFTER_HOURS",
		4: "MARKET_STATUS_CLOSED",
		5: "MARKET_STATUS_HALTED",
	}
	MarketStatus_value = map[string]int32{
		"MARKET_STATUS_UNSPECIFIED": 0,
		"MARKET_STATUS_REGULAR":     1,
		"MARKET_STATUS_PRE_MARKET":  2,
		"MARKET_STATUS_AFTER_HOURS": 3,
		"MARKET_STATUS_CLOSED":      4,
		"MARKET_STATUS_HALTED":      5,
	}
)

func (x MarketStatus) Enum() *MarketStatus {
	p := new(MarketStatus)
	*p = x
	return p
}

func (x MarketStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarketStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_v1_market_data_proto_enumTypes[1].Descriptor()
}

func (MarketStatus) Type() protoreflect.EnumType {
	return &file_market_data_v1_market_data_proto_enumTypes[1]
}

func (x MarketStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarketStatus.Descriptor instead.
func (MarketStatus) EnumDescriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{1}
}

type WsQuoteFrame_FrameType int32

const (
	WsQuoteFrame_FRAME_TYPE_UNSPECIFIED WsQuoteFrame_FrameType = 0
	WsQuoteFrame_FRAME_TYPE_SNAPSHOT    WsQuoteFrame_FrameType = 1 // subscribe 后立即推送的完整快照（所有 Quote 字段）
	WsQuoteFrame_FRAME_TYPE_TICK        WsQuoteFrame_FrameType = 2 // 注册用户 tick 级更新（只含变动字段，未变动字段为 proto3 零值）
	WsQuoteFrame_FRAME_TYPE_DELAYED     WsQuoteFrame_FrameType = 3 // 访客 T-15min 快照（每 5 秒，完整字段，delayed=true）
)

// Enum value maps for WsQuoteFrame_FrameType.
var (
	WsQuoteFrame_FrameType_name = map[int32]string{
		0: "FRAME_TYPE_UNSPECIFIED",
		1: "FRAME_TYPE_SNAPSHOT",
		2: "FRAME_TYPE_TICK",
		3: "FRAME_TYPE_DELAYED",
	}
	WsQuoteFrame_FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED": 0,
		"FRAME_TYPE_SNAPSHOT":    1,
		"FRAME_TYPE_TICK":        2,
		"FRAME_TYPE_DELAYED":     3,
	}
)

func (x WsQuoteFrame_FrameType) Enum() *WsQuoteFrame_FrameType {
	p := new(WsQuoteFrame_FrameType)
	*p = x
	return p
}

func (x WsQuoteFrame_FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WsQuoteFrame_FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_v1_market_data_proto_enumTypes[2].Descriptor()
}

func (WsQuoteFrame_FrameType) Type() protoreflect.EnumType {
	return &file_market_data_v1_market_data_proto_enumTypes[2]
}

func (x WsQuoteFrame_FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WsQuoteFrame_FrameType.Descriptor instead.
func (WsQuoteFrame_FrameType) EnumDescriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{5, 0}
}

// ──────────────────────────────────────────────────────────────────────────
// Quote — 实时行情快照
// 来源：market-api-spec.md §3.3 + §7.3
// 规范：
//
//	价格字段使用 string（禁止 float/double，财务编码规范 Rule 1）
//	时间戳使用 google.protobuf.Timestamp（UTC），JSON encoding → RFC 3339
//
// ──────────────────────────────────────────────────────────────────────────
type Quote struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Symbol string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                                       // 股票代码（美股字母如 "AAPL"，港股数字如 "0700"）
	Market Market                 `protobuf:"varint,2,opt,name=market,proto3,enum=brokerage.market_data.v1.Market" json:"market,omitempty"` // 市场
	// 价格字段（US: 4位小数；HK: 3位小数）
	Price        string       `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                                                                                // 最新成交价
	Change       string       `protobuf:"bytes,4,opt,name=change,proto3" json:"change,omitempty"`                                                                              // 涨跌额（相对前一 Regular Session 收盘价）
	ChangePct    string       `protobuf:"bytes,5,opt,name=change_pct,json=changePct,proto3" json:"change_pct,omitempty"`                                                       // 涨跌幅（%，2位小数，含正负号，如 "1.30" / "-0.82"）
	Volume       int64        `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`                                                                             // 当日累计成交量（股）
	Bid          string       `protobuf:"bytes,7,opt,name=bid,proto3" json:"bid,omitempty"`                                                                                    // 买一价
	Ask          string       `protobuf:"bytes,8,opt,name=ask,proto3" json:"ask,omitempty"`                                                                                    // 卖一价
	Open         string       `protobuf:"bytes,9,opt,name=open,proto3" json:"open,omitempty"`                                                                                  // 当日开盘价
	High         string       `protobuf:"bytes,10,opt,name=high,proto3" json:"high,omitempty"`                                                                                 // 当日最高价
	Low          string       `protobuf:"bytes,11,opt,name=low,proto3" json:"low,omitempty"`                                                                                   // 当日最低价
	PrevClose    string       `protobuf:"bytes,12,opt,name=prev_close,json=prevClose,proto3" json:"prev_close,omitempty"`                                                      // 前一 Regular Session 收盘价（涨跌基准，≠ 盘后收盘价）
	Turnover     string       `protobuf:"bytes,13,opt,name=turnover,proto3" json:"turnover,omitempty"`                                                                         // 当日成交额，带单位（如 "8.24B"）
	MarketStatus MarketStatus `protobuf:"varint,14,opt,name=market_status,json=marketStatus,proto3,enum=brokerage.market_data.v1.MarketStatus" json:"market_status,omitempty"` // 当前交易时段
	// 数据质量字段（来源：market-data-system.md Appendix D）
	// 展示阈值：5s；交易风控阈值：1s（由 Trading Engine 自行基于 timestamp 计算）
	IsStale       bool                   `protobuf:"varint,15,opt,name=is_stale,json=isStale,proto3" json:"is_stale,omitempty"`                  // true = 数据超过展示阈值 5s
	StaleSinceMs  int64                  `protobuf:"varint,16,opt,name=stale_since_ms,json=staleSinceMs,proto3" json:"stale_since_ms,omitempty"` // 陈旧持续时长（毫秒），is_stale=false 时为 0
	Delayed       bool                   `protobuf:"varint,17,opt,name=delayed,proto3" json:"delayed,omitempty"`                                 // true = 延时 15 分钟（访客）
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // 行情时间戳（UTC）；JSON encoding → RFC 3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_market_data_v1_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_v1_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *Quote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Quote) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

func (x *Quote) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Quote) GetChange() string {
	if x != nil {
		return x.Change
	}
	return ""
}

func (x *Quote) GetChangePct() string {
	if x != nil {
		return x.ChangePct
	}
	return ""
}

func (x *Quote) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Quote) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *Quote) GetAsk() string {
	if x != nil {
		return x.Ask
	}
	return ""
}

func (x *Quote) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Quote) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Quote) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Quote) GetPrevClose() string {
	if x != nil {
		return x.PrevClose
	}
	return ""
}

func (x *Quote) GetTurnover() string {
	if x != nil {
		return x.Turnover
	}
	return ""
}

func (x *Quote) GetMarketStatus() MarketStatus {
	if x != nil {
		return x.MarketStatus
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

func (x *Quote) GetIsStale() bool {
	if x != nil {
		return x.IsStale
	}
	return false
}

func (x *Quote) GetStaleSinceMs() int64 {
	if x != nil {
		return x.StaleSinceMs
	}
	return 0
}

func (x *Quote) GetDelayed() bool {
	if x != nil {
		return x.Delayed
	}
	return false
}

func (x *Quote) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"` // 最多 50 个，混合 US/HK 均可
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_market_data_v1_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_v1_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuoteRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        map[string]*Quote      `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key = symbol；symbol 不存在时不出现在 map 中
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`                                                                   // 快照时间（UTC）；JSON encoding → RFC 3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_market_data_v1_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_v1_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteResponse) GetQuotes() map[string]*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

func (x *GetQuoteResponse) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

type GetMarketStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        Market                 `protobuf:"varint,1,opt,name=market,proto3,enum=brokerage.market_data.v1.Market" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketStatusRequest) Reset() {
	*x = GetMarketStatusRequest{}
	mi := &file_market_data_v1_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketStatusRequest) ProtoMessage() {}

func (x *GetMarketStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_v1_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMarketStatusRequest) Descriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *GetMarketStatusRequest) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

type GetMarketStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        Market                 `protobuf:"varint,1,opt,name=market,proto3,enum=brokerage.market_data.v1.Market" json:"market,omitempty"`
	Status        MarketStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=brokerage.market_data.v1.MarketStatus" json:"status,omitempty"`
	SessionOpen   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=session_open,json=sessionOpen,proto3" json:"session_open,omitempty"`    // 当日交易时段开始（UTC）
	SessionClose  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=session_close,json=sessionClose,proto3" json:"session_close,omitempty"` // 当日交易时段结束（UTC）
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`                         // 状态查询时间（UTC）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketStatusResponse) Reset() {
	*x = GetMarketStatusResponse{}
	mi := &file_market_data_v1_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketStatusResponse) ProtoMessage() {}

func (x *GetMarketStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_v1_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMarketStatusResponse) Descriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *GetMarketStatusResponse) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_MARKET_UNSPECIFIED
}

func (x *GetMarketStatusResponse) GetStatus() MarketStatus {
	if x != nil {
		return x.Status
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

func (x *GetMarketStatusResponse) GetSessionOpen() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionOpen
	}
	return nil
}

func (x *GetMarketStatusResponse) GetSessionClose() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionClose
	}
	return nil
}

func (x *GetMarketStatusResponse) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

// ──────────────────────────────────────────────────────────────────────────
// WebSocket 二进制帧消息（服务端 → 客户端）
// 来源：services/market-data/docs/specs/websocket-spec.md v2.1（混合帧协议）
// 控制消息（auth、subscribe、ping 等）使用 JSON 文本帧，不走 proto。
// 所有行情数据（snapshot / tick / delayed）序列化为此消息的二进制帧。
// ──────────────────────────────────────────────────────────────────────────
type WsQuoteFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameType     WsQuoteFrame_FrameType `protobuf:"varint,1,opt,name=frame_type,json=frameType,proto3,enum=brokerage.market_data.v1.WsQuoteFrame_FrameType" json:"frame_type,omitempty"`
	Quote         *Quote                 `protobuf:"bytes,2,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsQuoteFrame) Reset() {
	*x = WsQuoteFrame{}
	mi := &file_market_data_v1_market_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsQuoteFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsQuoteFrame) ProtoMessage() {}

func (x *WsQuoteFrame) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_v1_market_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsQuoteFrame.ProtoReflect.Descriptor instead.
func (*WsQuoteFrame) Descriptor() ([]byte, []int) {
	return file_market_data_v1_market_data_proto_rawDescGZIP(), []int{5}
}

func (x *WsQuoteFrame) GetFrameType() WsQuoteFrame_FrameType {
	if x != nil {
		return x.FrameType
	}
	return WsQuoteFrame_FRAME_TYPE_UNSPECIFIED
}

func (x *WsQuoteFrame) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_market_data_v1_market_data_proto protoreflect.FileDescriptor

const file_market_data_v1_market_data_proto_rawDesc = "" +
	"\n" +
	" market_data/v1/market_data.proto\x12\x18brokerage.market_data.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x04\n" +
	"\x05Quote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x128\n" +
	"\x06market\x18\x02 \x01(\x0e2 .brokerage.market_data.v1.MarketR\x06market\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x16\n" +
	"\x06change\x18\x04 \x01(\tR\x06change\x12\x1d\n" +
	"\n" +
	"change_pct\x18\x05 \x01(\tR\tchangePct\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x03R\x06volume\x12\x10\n" +
	"\x03bid\x18\a \x01(\tR\x03bid\x12\x10\n" +
	"\x03ask\x18\b \x01(\tR\x03ask\x12\x12\n" +
	"\x04open\x18\t \x01(\tR\x04open\x12\x12\n" +
	"\x04high\x18\n" +
	" \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\v \x01(\tR\x03low\x12\x1d\n" +
	"\n" +
	"prev_close\x18\f \x01(\tR\tprevClose\x12\x1a\n" +
	"\bturnover\x18\r \x01(\tR\bturnover\x12K\n" +
	"\rmarket_status\x18\x0e \x01(\x0e2&.brokerage.market_data.v1.MarketStatusR\fmarketStatus\x12\x19\n" +
	"\bis_stale\x18\x0f \x01(\bR\aisStale\x12$\n" +
	"\x0estale_since_ms\x18\x10 \x01(\x03R\fstaleSinceMs\x12\x18\n" +
	"\adelayed\x18\x11 \x01(\bR\adelayed\x128\n" +
	"\ttimestamp\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"+\n" +
	"\x0fGetQuoteRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xef\x01\n" +
	"\x10GetQuoteResponse\x12N\n" +
	"\x06quotes\x18\x01 \x03(\v26.brokerage.market_data.v1.GetQuoteResponse.QuotesEntryR\x06quotes\x12/\n" +
	"\x05as_of\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\x1aZ\n" +
	"\vQuotesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.brokerage.market_data.v1.QuoteR\x05value:\x028\x01\"R\n" +
	"\x16GetMarketStatusRequest\x128\n" +
	"\x06market\x18\x01 \x01(\x0e2 .brokerage.market_data.v1.MarketR\x06market\"\xc4\x02\n" +
	"\x17GetMarketStatusResponse\x128\n" +
	"\x06market\x18\x01 \x01(\x0e2 .brokerage.market_data.v1.MarketR\x06market\x12>\n" +
	"\x06status\x18\x02 \x01(\x0e2&.brokerage.market_data.v1.MarketStatusR\x06status\x12=\n" +
	"\fsession_open\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vsessionOpen\x12?\n" +
	"\rsession_close\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fsessionClose\x12/\n" +
	"\x05as_of\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\"\x85\x02\n" +
	"\fWsQuoteFrame\x12O\n" +
	"\n" +
	"frame_type\x18\x01 \x01(\x0e20.brokerage.market_data.v1.WsQuoteFrame.FrameTypeR\tframeType\x125\n" +
	"\x05quote\x18\x02 \x01(\v2\x1f.brokerage.market_data.v1.QuoteR\x05quote\"m\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FRAME_TYPE_SNAPSHOT\x10\x01\x12\x13\n" +
	"\x0fFRAME_TYPE_TICK\x10\x02\x12\x16\n" +
	"\x12FRAME_TYPE_DELAYED\x10\x03*>\n" +
	"\x06Market\x12\x16\n" +
	"\x12MARKET_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMARKET_US\x10\x01\x12\r\n" +
	"\tMARKET_HK\x10\x02*\xb9\x01\n" +
	"\fMarketStatus\x12\x1d\n" +
	"\x19MARKET_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MARKET_STATUS_REGULAR\x10\x01\x12\x1c\n" +
	"\x18MARKET_STATUS_PRE_MARKET\x10\x02\x12\x1d\n" +
	"\x19MARKET_STATUS_AFTER_HOURS\x10\x03\x12\x18\n" +
	"\x14MARKET_STATUS_CLOSED\x10\x04\x12\x18\n" +
	"\x14MARKET_STATUS_HALTED\x10\x052\xee\x01\n" +
	"\x11MarketDataService\x12a\n" +
	"\bGetQuote\x12).brokerage.market_data.v1.GetQuoteRequest\x1a*.brokerage.market_data.v1.GetQuoteResponse\x12v\n" +
	"\x0fGetMarketStatus\x120.brokerage.market_data.v1.GetMarketStatusRequest\x1a1.brokerage.market_data.v1.GetMarketStatusResponseB@Z>github.com/hxiaodon/ai-broker/api/market_data/v1;market_datav1b\x06proto3"

var (
	file_market_data_v1_market_data_proto_rawDescOnce sync.Once
	file_market_data_v1_market_data_proto_rawDescData []byte
)

func file_market_data_v1_market_data_proto_rawDescGZIP() []byte {
	file_market_data_v1_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_v1_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_v1_market_data_proto_rawDesc), len(file_market_data_v1_market_data_proto_rawDesc)))
	})
	return file_market_data_v1_market_data_proto_rawDescData
}

var file_market_data_v1_market_data_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_market_data_v1_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_market_data_v1_market_data_proto_goTypes = []any{
	(Market)(0),                     // 0: brokerage.market_data.v1.Market
	(MarketStatus)(0),               // 1: brokerage.market_data.v1.MarketStatus
	(WsQuoteFrame_FrameType)(0),     // 2: brokerage.market_data.v1.WsQuoteFrame.FrameType
	(*Quote)(nil),                   // 3: brokerage.market_data.v1.Quote
	(*GetQuoteRequest)(nil),         // 4: brokerage.market_data.v1.GetQuoteRequest
	(*GetQuoteResponse)(nil),        // 5: brokerage.market_data.v1.GetQuoteResponse
	(*GetMarketStatusRequest)(nil),  // 6: brokerage.market_data.v1.GetMarketStatusRequest
	(*GetMarketStatusResponse)(nil), // 7: brokerage.market_data.v1.GetMarketStatusResponse
	(*WsQuoteFrame)(nil),            // 8: brokerage.market_data.v1.WsQuoteFrame
	nil,                             // 9: brokerage.market_data.v1.GetQuoteResponse.QuotesEntry
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
}
var file_market_data_v1_market_data_proto_depIdxs = []int32{
	0,  // 0: brokerage.market_data.v1.Quote.market:type_name -> brokerage.market_data.v1.Market
	1,  // 1: brokerage.market_data.v1.Quote.market_status:type_name -> brokerage.market_data.v1.MarketStatus
	10, // 2: brokerage.market_data.v1.Quote.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 3: brokerage.market_data.v1.GetQuoteResponse.quotes:type_name -> brokerage.market_data.v1.GetQuoteResponse.QuotesEntry
	10, // 4: brokerage.market_data.v1.GetQuoteResponse.as_of:type_name -> google.protobuf.Timestamp
	0,  // 5: brokerage.market_data.v1.GetMarketStatusRequest.market:type_name -> brokerage.market_data.v1.Market
	0,  // 6: brokerage.market_data.v1.GetMarketStatusResponse.market:type_name -> brokerage.market_data.v1.Market
	1,  // 7: brokerage.market_data.v1.GetMarketStatusResponse.status:type_name -> brokerage.market_data.v1.MarketStatus
	10, // 8: brokerage.market_data.v1.GetMarketStatusResponse.session_open:type_name -> google.protobuf.Timestamp
	10, // 9: brokerage.market_data.v1.GetMarketStatusResponse.session_close:type_name -> google.protobuf.Timestamp
	10, // 10: brokerage.market_data.v1.GetMarketStatusResponse.as_of:type_name -> google.protobuf.Timestamp
	2,  // 11: brokerage.market_data.v1.WsQuoteFrame.frame_type:type_name -> brokerage.market_data.v1.WsQuoteFrame.FrameType
	3,  // 12: brokerage.market_data.v1.WsQuoteFrame.quote:type_name -> brokerage.market_data.v1.Quote
	3,  // 13: brokerage.market_data.v1.GetQuoteResponse.QuotesEntry.value:type_name -> brokerage.market_data.v1.Quote
	4,  // 14: brokerage.market_data.v1.MarketDataService.GetQuote:input_type -> brokerage.market_data.v1.GetQuoteRequest
	6,  // 15: brokerage.market_data.v1.MarketDataService.GetMarketStatus:input_type -> brokerage.market_data.v1.GetMarketStatusRequest
	5,  // 16: brokerage.market_data.v1.MarketDataService.GetQuote:output_type -> brokerage.market_data.v1.GetQuoteResponse
	7,  // 17: brokerage.market_data.v1.MarketDataService.GetMarketStatus:output_type -> brokerage.market_data.v1.GetMarketStatusResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_market_data_v1_market_data_proto_init() }
func file_market_data_v1_market_data_proto_init() {
	if File_market_data_v1_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_v1_market_data_proto_rawDesc), len(file_market_data_v1_market_data_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_data_v1_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_v1_market_data_proto_depIdxs,
		EnumInfos:         file_market_data_v1_market_data_proto_enumTypes,
		MessageInfos:      file_market_data_v1_market_data_proto_msgTypes,
	}.Build()
	File_market_data_v1_market_data_proto = out.File
	file_market_data_v1_market_data_proto_goTypes = nil
	file_market_data_v1_market_data_proto_depIdxs = nil
}
