// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: market_data/v1/market_data.proto

package market_datav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_GetQuote_FullMethodName        = "/brokerage.market_data.v1.MarketDataService/GetQuote"
	MarketDataService_GetMarketStatus_FullMethodName = "/brokerage.market_data.v1.MarketDataService/GetMarketStatus"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────────────────────────────────
// gRPC Service — 供 Trading Engine 调用（预交易风控、交易时段判断）
// 来源：docs/contracts/market-data-to-trading.md v1
// ──────────────────────────────────────────────────────────────────────────
type MarketDataServiceClient interface {
	// GetQuote 按需查询最新报价，主要用于下单前的价格验证和风控检查。
	// Trading Engine 应检查 Quote.timestamp，若超过 1s 则视为数据过旧并拒绝市价单。
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
	// GetMarketStatus 查询市场当前交易时段，用于交易时段执行控制。
	GetMarketStatus(ctx context.Context, in *GetMarketStatusRequest, opts ...grpc.CallOption) (*GetMarketStatusResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetMarketStatus(ctx context.Context, in *GetMarketStatusRequest, opts ...grpc.CallOption) (*GetMarketStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketStatusResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetMarketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations should embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// ──────────────────────────────────────────────────────────────────────────
// gRPC Service — 供 Trading Engine 调用（预交易风控、交易时段判断）
// 来源：docs/contracts/market-data-to-trading.md v1
// ──────────────────────────────────────────────────────────────────────────
type MarketDataServiceServer interface {
	// GetQuote 按需查询最新报价，主要用于下单前的价格验证和风控检查。
	// Trading Engine 应检查 Quote.timestamp，若超过 1s 则视为数据过旧并拒绝市价单。
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
	// GetMarketStatus 查询市场当前交易时段，用于交易时段执行控制。
	GetMarketStatus(context.Context, *GetMarketStatusRequest) (*GetMarketStatusResponse, error)
}

// UnimplementedMarketDataServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedMarketDataServiceServer) GetMarketStatus(context.Context, *GetMarketStatusRequest) (*GetMarketStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketStatus not implemented")
}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue() {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetMarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetMarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetMarketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetMarketStatus(ctx, req.(*GetMarketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brokerage.market_data.v1.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetQuote",
			Handler:    _MarketDataService_GetQuote_Handler,
		},
		{
			MethodName: "GetMarketStatus",
			Handler:    _MarketDataService_GetMarketStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market_data/v1/market_data.proto",
}
