// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/money.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ──────────────────────────────────────────────────────────────────────────
// MoneyAmount — 货币金额（财务编码规范 Rule 1：禁止 float/double）
//
// 平台统一规范：
//
//	所有货币金额使用 decimal string，不得使用 float32 / float64。
//	精度要求：
//	  US 股票价格  — 4 位小数（如 "150.2500"）
//	  HK 股票价格  — 3 位小数（如 "89.750"）
//	  手续费/佣金  — 2 位小数（如 "1.50"）
//	  汇率         — 6 位小数（如 "7.823456"）
//
// ──────────────────────────────────────────────────────────────────────────
type MoneyAmount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// decimal string，如 "150.2500"；消费方用 shopspring/decimal (Go) 解析
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// ISO 4217 货币代码，如 "USD"、"HKD"
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyAmount) Reset() {
	*x = MoneyAmount{}
	mi := &file_common_v1_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyAmount) ProtoMessage() {}

func (x *MoneyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyAmount.ProtoReflect.Descriptor instead.
func (*MoneyAmount) Descriptor() ([]byte, []int) {
	return file_common_v1_money_proto_rawDescGZIP(), []int{0}
}

func (x *MoneyAmount) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MoneyAmount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_common_v1_money_proto protoreflect.FileDescriptor

const file_common_v1_money_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/money.proto\x12\x13brokerage.common.v1\"?\n" +
	"\vMoneyAmount\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrencyB6Z4github.com/hxiaodon/ai-broker/api/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_money_proto_rawDescOnce sync.Once
	file_common_v1_money_proto_rawDescData []byte
)

func file_common_v1_money_proto_rawDescGZIP() []byte {
	file_common_v1_money_proto_rawDescOnce.Do(func() {
		file_common_v1_money_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_money_proto_rawDesc), len(file_common_v1_money_proto_rawDesc)))
	})
	return file_common_v1_money_proto_rawDescData
}

var file_common_v1_money_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_money_proto_goTypes = []any{
	(*MoneyAmount)(nil), // 0: brokerage.common.v1.MoneyAmount
}
var file_common_v1_money_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_money_proto_init() }
func file_common_v1_money_proto_init() {
	if File_common_v1_money_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_money_proto_rawDesc), len(file_common_v1_money_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_money_proto_goTypes,
		DependencyIndexes: file_common_v1_money_proto_depIdxs,
		MessageInfos:      file_common_v1_money_proto_msgTypes,
	}.Build()
	File_common_v1_money_proto = out.File
	file_common_v1_money_proto_goTypes = nil
	file_common_v1_money_proto_depIdxs = nil
}
