// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hxiaodon/ai-broker/services/market-data/internal/conf"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/feed"
	kafkaConsumer "github.com/hxiaodon/ai-broker/services/market-data/internal/kafka/consumer"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/kafka/outbox"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/kline"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote/app"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote/infra/mysql"
	redisInfra "github.com/hxiaodon/ai-broker/services/market-data/internal/quote/infra/redis"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/search"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/server"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/watchlist"
	redis2 "github.com/redis/go-redis/v9"
	"github.com/segmentio/kafka-go"
	"go.uber.org/zap"
	mysql2 "gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config, logger *zap.Logger) (*App, func(), error) {
	httpAddr := ProvideHTTPAddr(cfg)
	client, cleanup, err := ProvideRedis(cfg)
	if err != nil {
		return nil, nil, err
	}
	quoteCacheRepository := redisInfra.NewQuoteCacheRepository(client)
	delayedRingBuffer := redisInfra.NewDelayedRingBuffer(client)
	db, cleanup2, err := ProvideDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	quoteRepository := mysql.NewQuoteRepository(db)
	staleDetector := quote.ProvideStaleDetector()
	getQuoteUsecase := app.NewGetQuoteUsecase(quoteCacheRepository, quoteRepository, staleDetector, delayedRingBuffer, logger)
	marketStatusRepository := mysql.NewMarketStatusRepository(db)
	getMarketStatusUsecase := app.NewGetMarketStatusUsecase(marketStatusRepository)
	handler := quote.NewHandler(getQuoteUsecase, getMarketStatusUsecase)
	mySQLKLineRepo := kline.NewMySQLKLineRepo(db)
	aggregateKLineUsecase := kline.NewAggregateKLineUsecase(mySQLKLineRepo)
	tickAccumulator := kline.NewTickAccumulator(aggregateKLineUsecase)
	klineScheduler := kline.NewKLineScheduler(tickAccumulator)
	getKLinesUsecase := kline.NewGetKLinesUsecase(mySQLKLineRepo)
	klineHandler := kline.NewHandler(getKLinesUsecase)
	mySQLWatchlistRepo := watchlist.NewMySQLWatchlistRepo(db)
	getWatchlistUsecase := watchlist.NewGetWatchlistUsecase(mySQLWatchlistRepo)
	mySQLStockSearchRepo := search.NewMySQLStockSearchRepo(db)
	addToWatchlistUsecase := watchlist.NewAddToWatchlistUsecase(mySQLWatchlistRepo, mySQLStockSearchRepo)
	removeFromWatchlistUsecase := watchlist.NewRemoveFromWatchlistUsecase(mySQLWatchlistRepo)
	watchlistHandler := watchlist.NewHandler(getWatchlistUsecase, addToWatchlistUsecase, removeFromWatchlistUsecase)
	redisHotSearchRepo := search.NewRedisHotSearchRepo(client)
	searchStocksUsecase := search.NewSearchStocksUsecase(mySQLStockSearchRepo, redisHotSearchRepo)
	getHotSearchUsecase := search.NewGetHotSearchUsecase(redisHotSearchRepo)
	searchHandler := search.NewHandler(searchStocksUsecase, getHotSearchUsecase)
	httpServer := server.NewHTTPServer(httpAddr, handler, klineHandler, watchlistHandler, searchHandler)
	grpcAddr := ProvideGRPCAddr(cfg)
	grpcServer, err := server.NewGRPCServer(grpcAddr)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	wsServer := server.NewWSServer(logger, quoteCacheRepository)
	wsAddr := ProvideWSAddr(cfg)
	massiveClient := feed.ProvideMassiveClient(cfg)
	outboxRepository := mysql.NewOutboxRepository(db)
	txFunc := mysql.NewTxFunc(db)
	updateQuoteUsecase := app.NewUpdateQuoteUsecase(quoteRepository, quoteCacheRepository, outboxRepository, txFunc, staleDetector, delayedRingBuffer, logger)
	worker := feed.ProvideWorker(massiveClient, updateQuoteUsecase, tickAccumulator, logger)
	mainWriter := ProvideKafkaWriter(cfg)
	dlqWriter := ProvideDLQWriter(cfg)
	string2 := ProvideDLQTopic(cfg)
	outboxWorker := outbox.NewWorker(db, mainWriter, dlqWriter, string2, logger)
	quoteConsumer := kafkaConsumer.NewQuoteConsumer(cfg.Kafka.Brokers, "market-data-ws", wsServer, logger)
	marketScheduler, err := app.NewMarketScheduler(marketStatusRepository, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mainApp := NewApp(httpServer, grpcServer, wsServer, wsAddr, worker, outboxWorker, quoteConsumer, klineScheduler, marketScheduler, logger)
	return mainApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// ProvideDB creates a GORM DB connection.
func ProvideDB(cfg *conf.Config) (*gorm.DB, func(), error) {
	db, err := gorm.Open(mysql2.Open(cfg.Data.MySQL.DSN), &gorm.Config{})
	if err != nil {
		return nil, nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		_ = sqlDB.Close()
	}
	return db, cleanup, nil
}

// ProvideRedis creates a Redis client.
func ProvideRedis(cfg *conf.Config) (*redis2.Client, func(), error) {
	rdb := redis2.NewClient(&redis2.Options{
		Addr:     cfg.Data.Redis.Addr,
		Password: cfg.Data.Redis.Password,
		DB:       cfg.Data.Redis.DB,
	})
	cleanup := func() {
		_ = rdb.Close()
	}
	return rdb, cleanup, nil
}

// ProvideKafkaWriter creates a Kafka writer for the outbox worker.
func ProvideKafkaWriter(cfg *conf.Config) *kafka.Writer {
	return &kafka.Writer{
		Addr:     kafka.TCP(cfg.Kafka.Brokers...),
		Balancer: &kafka.LeastBytes{},
	}
}

// ProvideDLQWriter creates a dedicated Kafka writer for the Dead Letter Queue.
// Using a separate writer ensures DLQ writes use a distinct connection and can
// be routed to a different broker cluster if needed.
func ProvideDLQWriter(cfg *conf.Config) *kafka.Writer {
	return &kafka.Writer{
		Addr:     kafka.TCP(cfg.Kafka.Brokers...),
		Balancer: &kafka.LeastBytes{},
	}
}

// ProvideDLQTopic extracts DLQ topic from config.
func ProvideDLQTopic(cfg *conf.Config) string {
	if cfg.Kafka.DLQTopic == "" {
		return "market-data.dlq"
	}
	return cfg.Kafka.DLQTopic
}

// ProvideHTTPAddr extracts the HTTP address from config.
func ProvideHTTPAddr(cfg *conf.Config) server.HTTPAddr {
	return server.HTTPAddr(cfg.Server.HTTP.Addr)
}

// ProvideGRPCAddr extracts the gRPC address from config.
func ProvideGRPCAddr(cfg *conf.Config) server.GRPCAddr {
	return server.GRPCAddr(cfg.Server.GRPC.Addr)
}

// ProvideWSAddr extracts the WebSocket server address from config.
func ProvideWSAddr(cfg *conf.Config) server.WSAddr {
	if cfg.Server.WS.Addr == "" {
		return server.WSAddr(":8082")
	}
	return server.WSAddr(cfg.Server.WS.Addr)
}

