// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hxiaodon/ai-broker/services/market-data/internal/conf"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/feed"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/kafka/outbox"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/kline"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote/app"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote/infra/mysql"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/quote/infra/redis"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/search"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/server"
	"github.com/hxiaodon/ai-broker/services/market-data/internal/watchlist"
	redis2 "github.com/redis/go-redis/v9"
	"github.com/segmentio/kafka-go"
	"go.uber.org/zap"
	mysql2 "gorm.io/driver/mysql"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initApp(cfg *conf.Config, logger *zap.Logger) (*App, func(), error) {
	httpAddr := ProvideHTTPAddr(cfg)
	client, cleanup, err := ProvideRedis(cfg)
	if err != nil {
		return nil, nil, err
	}
	quoteCacheRepository := redis.NewQuoteCacheRepository(client)
	db, cleanup2, err := ProvideDB(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	quoteRepository := mysql.NewQuoteRepository(db)
	staleDetector := quote.ProvideStaleDetector()
	getQuoteUsecase := app.NewGetQuoteUsecase(quoteCacheRepository, quoteRepository, staleDetector, logger)
	marketStatusRepository := mysql.NewMarketStatusRepository(db)
	getMarketStatusUsecase := app.NewGetMarketStatusUsecase(marketStatusRepository)
	handler := quote.NewHandler(getQuoteUsecase, getMarketStatusUsecase)
	mySQLKLineRepo := kline.NewMySQLKLineRepo(db)
	getKLinesUsecase := kline.NewGetKLinesUsecase(mySQLKLineRepo)
	klineHandler := kline.NewHandler(getKLinesUsecase)
	mySQLWatchlistRepo := watchlist.NewMySQLWatchlistRepo(db)
	getWatchlistUsecase := watchlist.NewGetWatchlistUsecase(mySQLWatchlistRepo)
	mySQLStockSearchRepo := search.NewMySQLStockSearchRepo(db)
	addToWatchlistUsecase := watchlist.NewAddToWatchlistUsecase(mySQLWatchlistRepo, mySQLStockSearchRepo)
	removeFromWatchlistUsecase := watchlist.NewRemoveFromWatchlistUsecase(mySQLWatchlistRepo)
	watchlistHandler := watchlist.NewHandler(getWatchlistUsecase, addToWatchlistUsecase, removeFromWatchlistUsecase)
	redisHotSearchRepo := search.NewRedisHotSearchRepo(client)
	searchStocksUsecase := search.NewSearchStocksUsecase(mySQLStockSearchRepo, redisHotSearchRepo)
	getHotSearchUsecase := search.NewGetHotSearchUsecase(redisHotSearchRepo)
	searchHandler := search.NewHandler(searchStocksUsecase, getHotSearchUsecase)
	httpServer := server.NewHTTPServer(httpAddr, handler, klineHandler, watchlistHandler, searchHandler)
	grpcAddr := ProvideGRPCAddr(cfg)
	grpcServer, err := server.NewGRPCServer(grpcAddr)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	massiveClient := feed.ProvideMassiveClient(cfg)
	outboxRepository := mysql.NewOutboxRepository(db)
	txFunc := mysql.NewTxFunc(db)
	updateQuoteUsecase := app.NewUpdateQuoteUsecase(quoteRepository, quoteCacheRepository, outboxRepository, txFunc, staleDetector, logger)
	worker := feed.ProvideWorker(massiveClient, updateQuoteUsecase, logger)
	writer := ProvideKafkaWriter(cfg)
	outboxWorker := outbox.NewWorker(db, writer, logger)
	mainApp := NewApp(httpServer, grpcServer, worker, outboxWorker, logger)
	return mainApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// ProvideDB creates a GORM DB connection.
func ProvideDB(cfg *conf.Config) (*gorm.DB, func(), error) {
	db, err := gorm.Open(mysql2.Open(cfg.Data.MySQL.DSN), &gorm.Config{})
	if err != nil {
		return nil, nil, err
	}
	sqlDB, err := db.DB()
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		_ = sqlDB.Close()
	}
	return db, cleanup, nil
}

// ProvideRedis creates a Redis client.
func ProvideRedis(cfg *conf.Config) (*redis2.Client, func(), error) {
	rdb := redis2.NewClient(&redis2.Options{
		Addr:     cfg.Data.Redis.Addr,
		Password: cfg.Data.Redis.Password,
		DB:       cfg.Data.Redis.DB,
	})
	cleanup := func() {
		_ = rdb.Close()
	}
	return rdb, cleanup, nil
}

// ProvideKafkaWriter creates a Kafka writer for the outbox worker.
func ProvideKafkaWriter(cfg *conf.Config) *kafka.Writer {
	return &kafka.Writer{
		Addr:     kafka.TCP(cfg.Kafka.Brokers...),
		Balancer: &kafka.LeastBytes{},
	}
}

// ProvideHTTPAddr extracts the HTTP address from config.
func ProvideHTTPAddr(cfg *conf.Config) server.HTTPAddr {
	return server.HTTPAddr(cfg.Server.HTTP.Addr)
}

// ProvideGRPCAddr extracts the gRPC address from config.
func ProvideGRPCAddr(cfg *conf.Config) server.GRPCAddr {
	return server.GRPCAddr(cfg.Server.GRPC.Addr)
}
