// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kline": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns OHLCV candlestick bars for a symbol and interval. Historical prices use split+dividend backward adjustment.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kline"
                ],
                "summary": "Get K-line (candlestick) data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock symbol (e.g. AAPL, 00700)",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "1min",
                            "5min",
                            "15min",
                            "30min",
                            "1h",
                            "1D",
                            "1W",
                            "1M"
                        ],
                        "type": "string",
                        "default": "1D",
                        "description": "Bar interval",
                        "name": "interval",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 200,
                        "description": "Maximum number of bars to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time in RFC 3339 format (e.g. 2024-01-01T00:00:00Z)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time in RFC 3339 format (e.g. 2024-12-31T23:59:59Z)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_kline.KLine"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/market/status": {
            "get": {
                "description": "Returns the current trading phase and session times for a given market (US or HK).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quote"
                ],
                "summary": "Get market trading status",
                "parameters": [
                    {
                        "enum": [
                            "US",
                            "HK"
                        ],
                        "type": "string",
                        "default": "US",
                        "description": "Market identifier (US or HK)",
                        "name": "market",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.MarketStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/quote": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the latest quote snapshot for a given symbol. For guest users the price is delayed 15 minutes and labeled accordingly.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "quote"
                ],
                "summary": "Get real-time quote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock symbol (e.g. AAPL, 00700)",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.Quote"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Full-text search across stock symbols and company names. Supports US (NYSE/NASDAQ) and HK (HKEX) markets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search stocks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (symbol prefix or company name keyword)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "US",
                            "HK"
                        ],
                        "type": "string",
                        "description": "Filter by market",
                        "name": "market",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Maximum number of results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_search.Stock"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search/hot": {
            "get": {
                "description": "Returns the top-N most searched symbols in the last 24 hours, ranked by search frequency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Get hot search rankings",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of top symbols to return",
                        "name": "n",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_search.HotSearchItem"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/watchlist": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all symbols in the user's watchlist with latest quotes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Get user watchlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID (temporary; production uses JWT claims)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_watchlist.WatchlistItem"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a stock symbol to the user's watchlist. Duplicate symbols are ignored.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Add symbol to watchlist",
                "parameters": [
                    {
                        "description": "Symbol to add",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_watchlist.addWatchlistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes a stock symbol from the user's watchlist. No-op if symbol is not present.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "watchlist"
                ],
                "summary": "Remove symbol from watchlist",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID (temporary; production uses JWT claims)",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stock symbol to remove",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.Market": {
            "type": "string",
            "enum": [
                "US",
                "HK"
            ],
            "x-enum-comments": {
                "MarketHK": "HKEX",
                "MarketUS": "NYSE/NASDAQ"
            },
            "x-enum-descriptions": [
                "NYSE/NASDAQ",
                "HKEX"
            ],
            "x-enum-varnames": [
                "MarketUS",
                "MarketHK"
            ]
        },
        "github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.MarketStatus": {
            "type": "object",
            "properties": {
                "market": {
                    "$ref": "#/definitions/github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.Market"
                },
                "phase": {
                    "$ref": "#/definitions/github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.TradingPhase"
                },
                "updatedAt": {
                    "description": "Always UTC",
                    "type": "string"
                }
            }
        },
        "github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.Quote": {
            "type": "object",
            "properties": {
                "ask": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "askSize": {
                    "type": "integer",
                    "format": "int64"
                },
                "bid": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "bidSize": {
                    "type": "integer",
                    "format": "int64"
                },
                "change": {
                    "description": "shopspring/decimal — never float64 — Price - PrevClose (unadjusted)",
                    "type": "number"
                },
                "changePct": {
                    "description": "shopspring/decimal — never float64 — Change / PrevClose * 100",
                    "type": "number"
                },
                "high": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "isStale": {
                    "description": "true if quote exceeds stale threshold",
                    "type": "boolean"
                },
                "lastUpdatedAt": {
                    "description": "Always UTC",
                    "type": "string"
                },
                "low": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "market": {
                    "$ref": "#/definitions/github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.Market"
                },
                "open": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "prevClose": {
                    "description": "shopspring/decimal — never float64 — previous Regular Session close",
                    "type": "number"
                },
                "price": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "github_com_hxiaodon_ai-broker_services_market-data_internal_quote_domain.TradingPhase": {
            "type": "string",
            "enum": [
                "PRE_MARKET",
                "OPEN",
                "LUNCH_BREAK",
                "POST_MARKET",
                "CLOSED"
            ],
            "x-enum-comments": {
                "PhaseLunchBreak": "HK only"
            },
            "x-enum-descriptions": [
                "",
                "",
                "HK only",
                "",
                ""
            ],
            "x-enum-varnames": [
                "PhasePreMarket",
                "PhaseOpen",
                "PhaseLunchBreak",
                "PhasePostMarket",
                "PhaseClosed"
            ]
        },
        "internal_kline.Interval": {
            "type": "string",
            "enum": [
                "1min",
                "5min",
                "15min",
                "30min",
                "1h",
                "1D",
                "1W",
                "1M"
            ],
            "x-enum-varnames": [
                "Interval1Min",
                "Interval5Min",
                "Interval15Min",
                "Interval30Min",
                "Interval1H",
                "Interval1D",
                "Interval1W",
                "Interval1M"
            ]
        },
        "internal_kline.KLine": {
            "type": "object",
            "properties": {
                "adjusted": {
                    "description": "true if prices are adjusted for corporate actions",
                    "type": "boolean"
                },
                "close": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "endTime": {
                    "description": "Always UTC — end of the candle period",
                    "type": "string"
                },
                "high": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "interval": {
                    "$ref": "#/definitions/internal_kline.Interval"
                },
                "low": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "open": {
                    "description": "shopspring/decimal — never float64",
                    "type": "number"
                },
                "startTime": {
                    "description": "Always UTC — start of the candle period",
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "volume": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "internal_search.HotSearchItem": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "score": {
                    "description": "Redis sorted set score — display ranking only, not financial",
                    "type": "number",
                    "format": "float64"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "internal_search.Stock": {
            "type": "object",
            "properties": {
                "exchange": {
                    "description": "\"NYSE\", \"NASDAQ\", \"HKEX\"",
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "market": {
                    "description": "\"US\" or \"HK\"",
                    "type": "string"
                },
                "name": {
                    "description": "Company name",
                    "type": "string"
                },
                "nameCN": {
                    "description": "Chinese company name",
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "internal_watchlist.WatchlistItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Always UTC",
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "market": {
                    "description": "\"US\" or \"HK\"",
                    "type": "string"
                },
                "sortOrder": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer",
                    "format": "int64"
                }
            }
        },
        "internal_watchlist.addWatchlistRequest": {
            "type": "object",
            "properties": {
                "market": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
